name: Keep Render Service Alive

on:
  schedule:
    # Se ejecuta cada 14 minutos
    - cron: '*/14 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URL
        run: curl -s "https://encuesta-docente.onrender.com/" > /dev/null
